### ISSUE TITLE
Windows: first character input lost on successive programs

### ISSUE THREAD

**Issue by jtackaberry** [charmbracelet/bubbletea#1167]
**Describe the bug**

On Windows, if multiple Tea programs are run successively within the same process, the first program runs fine, but subsequent programs lose the first key pressed.  The key is silently eaten, after which point the program appears to operate properly until it terminates.  Then rinse/repeat for subsequent Tea programs.

This does not occur on Linux or Mac.

**Setup**

 - OS: Windows
 - Shell: cmd and Powershell (both affected)
 - Terminal Emulator: Windows Terminal, Windows Powershell Console, Command Prompt
 - Terminal Multiplexer: none

**To Reproduce**

1. Build the example in the source code section for windows
2. Run it
3. Type some keys for the first input prompt ("Test 0") and note that it works fine
4. Type a key for the second input prompt ("Test 1") and note that the first key is eaten, and subsequent keys presses are registered

**Source Code**

```go
package main

import (
	"fmt"

	"github.com/charmbracelet/bubbles/cursor"
	"github.com/charmbracelet/bubbles/textinput"
	tea "github.com/charmbracelet/bubbletea"
)

func Input(prompt, value string) {
	ti := textinput.New()
	ti.Prompt = prompt
	ti.Focus()
	p := tea.NewProgram(inputModel{textInput: ti})
	p.Run()
}

type inputModel struct {
	textInput textinput.Model
	quitting  bool
}

func (m inputModel) Init() tea.Cmd {
	return nil
}

func (m inputModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmd tea.Cmd

	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.Type {
		case tea.KeyEnter:
			m.textInput.Cursor.SetMode(cursor.CursorHide)
			m.quitting = true
			return m, tea.Quit
		}
	}
	m.textInput, cmd = m.textInput.Update(msg)
	return m, cmd
}

func (m inputModel) View() string {
	str := m.textInput.View()
	if m.quitting {
		return str + "\n"
	}
	return str
}

func main() {
	for i := range 2 {
		Input(fmt.Sprintf("Test %d: ", i), "default")
	}
}
```

**Expected behavior**

The first key on subsequent Tea programs should not be lost.

**Screenshots**

![image](https://github.com/user-attachments/assets/ebb27587-525b-48c5-ac4b-8fe00beffbb2)

**Comment by Denish3436** [comment]
i would like to work on this, could you assign me

**Comment by meowgorithm** [comment]
Go for it, @Denish3436 ✌️

**Comment by Denish3436** [comment]
Hii @meowgorithm , can you please review my PR

**Comment by meowgorithm** [comment]
Hey @Denish3436! Ayman's reviewed it in #1180. Let's track progress over there.

**Comment by aymanbagabas** [comment]
@Denish3436 This should be fixed in `v2-exp`

**Comment by nojaf** [comment]
Hi @aymanbagabas, I'm still getting that problem with the `v2-exp` branch on Windows.

Example file:

```go
package main

import (
	"fmt"
	"log"
	"os"

	tea "github.com/charmbracelet/bubbletea/v2"
)

type model struct {
	v string
}

func NewModel() model {
	return model{v: ""}
}

func (m model) Init() (tea.Model, tea.Cmd) {
	return m, nil
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {

	// Is it a key press?
	case tea.KeyMsg:
		log.Println("key pressed:", msg.String())

		switch msg.String() {
		case "ctrl+c", "enter":
			return m, tea.Quit
		default:
			m.v += msg.String()
		}
	}

	return m, nil
}

func (m model) View() string {
	return "> " + m.v
}

func main() {
	file := "debug.log"

	// Check if the file exists
	if _, err := os.Stat(file); err == nil {
		// File exists, attempt to remove it
		if err := os.Remove(file); err != nil {
			// Handle error during removal
			panic(err)
		}
	} else if !os.IsNotExist(err) {
		// Handle unexpected error during Stat
		panic(err)
	}

	f, err := tea.LogToFile(file, "debug")
	if err != nil {
		fmt.Println("fatal:", err)
		os.Exit(1)
	}
	defer f.Close()

	p := tea.NewProgram(NewModel())
	if _, err := p.Run(); err != nil {
		fmt.Printf("Alas, there's been an error: %v", err)
		os.Exit(1)
	}

	p2 := tea.NewProgram(NewModel())
	if _, err := p2.Run(); err != nil {
		fmt.Printf("Alas, there's been an error 2: %v", err)
		os.Exit(1)
	}
}
```

A keypress is swallowed for the second program and each key is duplicated in the stdout:

Actual key presses: `a`,`b`,`c`,`enter`,`d`,`e`,`f`,`enter`

```
debug 2024/11/27 16:29:30 key pressed: a
debug 2024/11/27 16:29:30 key pressed: a
debug 2024/11/27 16:29:31 key pressed: b
debug 2024/11/27 16:29:31 key pressed: b
debug 2024/11/27 16:29:31 key pressed: c
debug 2024/11/27 16:29:31 key pressed: c
debug 2024/11/27 16:29:32 key pressed: enter
debug 2024/11/27 16:29:32 key pressed: enter
debug 2024/11/27 16:29:35 key pressed: e
debug 2024/11/27 16:29:35 key pressed: e
debug 2024/11/27 16:29:36 key pressed: f
debug 2024/11/27 16:29:36 key pressed: f
debug 2024/11/27 16:29:36 key pressed: enter
debug 2024/11/27 16:29:36 key pressed: enter
``` 

Any pointers

**Comment by aymanbagabas** [comment]
> Hi @aymanbagabas, I'm still getting that problem with the `v2-exp` branch on Windows.

Hi @nojaf. You're getting duplicate keys because you're listening for `tea.KeyMsg` which accounts for **both** `tea.KeyPressMsg` _and_ `tea.KeyReleaseMsg`.

This should fix that for you:

```diff
-	case tea.KeyMsg:
+	case tea.KeyPressMsg:
```

Now, running your examples with the latest `v2-exp` branch gives me this output. 
```
PS C:\Users\Ayman\Source\charmbracelet\bubbletea\examples> Get-Content -path .\debug.log -wait
debug 2024/11/27 11:23:29 key pressed: a
debug 2024/11/27 11:23:30 key pressed: b
debug 2024/11/27 11:23:30 key pressed: c
debug 2024/11/27 11:23:33 key pressed: d
debug 2024/11/27 11:23:34 key pressed: enter
debug 2024/11/27 11:23:35 key pressed: e
debug 2024/11/27 11:23:36 key pressed: f
debug 2024/11/27 11:23:39 key pressed: g
debug 2024/11/27 11:23:40 key pressed: h
debug 2024/11/27 11:23:41 key pressed: enter
```

I'm using Windows Terminal Preview on Windows 11 with the default PowerShell version.

**Comment by nojaf** [comment]
Hey @aymanbagabas, thanks for the quick feedback!

The `KeyPressMsg` fix does indeed solve the duplicate keys.
As for the missing one, it does still pop up in `vscode` termninal for me.
Not in the Windows Terminal but the thing vscode uses. (both using latest `pwsh`)

![bubbletea_vscode](https://github.com/user-attachments/assets/c6c2174e-e496-49b7-b621-6db1436f631c)

```
debug 2024/11/27 17:42:53 key pressed: a
debug 2024/11/27 17:42:53 key pressed: b
debug 2024/11/27 17:42:54 key pressed: c
debug 2024/11/27 17:42:54 key pressed: enter
debug 2024/11/27 17:42:56 key pressed: e
debug 2024/11/27 17:42:56 key pressed: f
debug 2024/11/27 17:42:56 key pressed: enter
```

I did press `d` and it is still missing there.

**Comment by LinusMoser** [comment]
I'm seeing a similar issue on Windows, where the first key after a `tea.NewProgram().Run()` is swallowed. The following snippet causes the first character of the `fmt.Scanln` to be ignored in my case:
```go
_, err := tea.NewProgram(list.NewList()).Run()
if err!=nil {
	return nil, err
}
input := ""
fmt.Scanln(&input)
```

When investigating the problem, I found that in the [ìnputreader_windows.go](https://github.com/charmbracelet/bubbletea/blob/eb7e3d0884f5976bbd94144bf3495ecb935dbce4/inputreader_windows.go) a custom coninput reader for windows is implemented. I don't really understand why this is done, as far as I understand it this inputreader file exists because reading from os.Stdin cannot be unblocked without an explicit write to it (which causes exactly the symptoms I have). To solve the issue with the blocked os.Stdin there is a platform specific implementation on `"github.com/muesli/cancelreader"` which is actually already in use as a fallback reader. After removing the custom inputreader and the custom coninput reader loop in [key_windows.go](https://github.com/charmbracelet/bubbletea/blob/eb7e3d0884f5976bbd94144bf3495ecb935dbce4/key_windows.go) the issue resolved itself as it now only relies on the cancelreader which correctly cancels upon cancellation.

I have a working fork at https://github.com/megakuul/bubbletea. My question is: why is a custom Windows coninput reader used? I'm not deeply familiar with the project and might be missing some requirements tied to the custom reader.

**Comment by aymanbagabas** [comment]
Hey @LinusMoser, could you try the v2-exp branch and see if it solves your issue? You can do `go get github.com/charmbracelet/bubbletea/v2@v2-exp`. Keep in mind that this is still a prerelease.

**Comment by awoodbeck** [comment]
I ran into this issue last week on Windows and did some debugging. What I found was that the read loop goroutine was blocked [reading from input](https://github.com/charmbracelet/bubbletea/blob/main/key_windows.go#L28) and did not properly return when the program's `Run` method returned. This caused the very next input to be swallowed up by the read loop, at which time the read loop would return because [its context was canceled](https://github.com/charmbracelet/bubbletea/blob/main/key_windows.go#L85).

The reason the input reader didn't unblock is likely because it's making a [windows.CancelIo](https://github.com/charmbracelet/bubbletea/blob/main/inputreader_windows.go#L60) call on the input handle. Per Windows' [docs](https://learn.microsoft.com/en-us/windows/win32/fileio/cancelio), `CancelIo` will not cancel I/O operations across threads. Since the read loop is in its own goroutine, it's very likely on a separate thread than the one calling `windows.CancelIo()`. Instead, [CancelIoEx](https://learn.microsoft.com/en-us/windows/win32/fileio/cancelioex-func) should properly close the input handle, unblock the input reader, and terminate the read loop goroutine.

The above PR adds the `CancelIoEx` call, and resolved the issue for me locally.

**Comment by LinusMoser** [comment]
@aymanbagabas with the v2-exp branch it does not solve the issues, instead it seems to receive keyboard messages even if no keys are pressed (notice that it selects the first list item immediately without pressing any key):

https://github.com/user-attachments/assets/8d9dbc25-528b-4154-9b49-2377c6d3c3c9

For reference:
```bash
require (
	github.com/charmbracelet/bubbles/v2 v2.0.0-alpha.2.0.20250131212117-b2e3cc537170
	github.com/charmbracelet/bubbletea/v2 v2.0.0-alpha.2.0.20250203222705-2e91ec2235cd
	github.com/charmbracelet/lipgloss/v2 v2.0.0-alpha.2.0.20250127205353-a4c540623882
)
```

I think the issue in v1 is actually solved by the proposal from @awoodbeck, this does also work for me.

**Comment by aymanbagabas** [comment]
> Hey [@aymanbagabas](https://github.com/aymanbagabas), thanks for the quick feedback!
> 
> The `KeyPressMsg` fix does indeed solve the duplicate keys. As for the missing one, it does still pop up in `vscode` termninal for me. Not in the Windows Terminal but the thing vscode uses. (both using latest `pwsh`)


I can always reproduce the issue in the VSCode terminal, even with the fix @awoodbeck introduced, same goes for v2-exp. The fix works on Windows Terminal and cmd.exe but not VSCode terminal. Which leads me to think that this is related to VSCode terminal 🤔

**Comment by aymanbagabas** [comment]
> [@aymanbagabas](https://github.com/aymanbagabas) with the v2-exp branch it does not solve the issue, instead it seems to receive keyboard messages even if no keys are pressed (notice that it selects the first list item immediately without pressing any key):
> 

Could you provide the example you used with v2-exp?

**Comment by LinusMoser** [comment]
@aymanbagabas I have previously tested it directly in my application code. Here is a very simple example that reproduces the issue:
[https://github.com/LinusMoser/bubbletea-v2-windows-input-issue](https://github.com/LinusMoser/bubbletea-v2-windows-input-issue)

It seems to only occur when I read from `stdin` before opening the tea application. For testing, I used the Windows terminal `wt.exe` with powershell

**Comment by joshallenit** [comment]
Hi, this is still an issue with `v2-exp` as well as `v2.0.0-alpha.2`.

**Comment by joshallenit** [comment]
The issue in my testing is that `windows.CancelIoEx` returns an error "Element not found", and the character goes to the "cancelled" coninput.ReadNConsoleInputs call, which is then discarded because "con.isCanceled()"

This issue leads to be believe that cancelling console input on Windows is not possible, and a new approach is required: https://github.com/microsoft/terminal/issues/12143

**Comment by aymanbagabas** [comment]
> The issue in my testing is that `windows.CancelIoEx` returns an error "Element not found", and the character goes to the "cancelled" coninput.ReadNConsoleInputs call, which is then discarded because "con.isCanceled()"

Hey @joshallenit, thank you for bringing this to our attention again. While I cannot reproduce this with the latest v2-exp 2ce107c, could you provide a minimal reproducible example for this case?

I'm testing this against v2-exp using the following example:

```go
package main

import (
	"fmt"

	"github.com/charmbracelet/bubbles/v2/textinput"
	tea "github.com/charmbracelet/bubbletea/v2"
)

func Input(prompt, value string) {
	ti := textinput.New()
	ti.Prompt = prompt
	ti.Focus()
	p := tea.NewProgram(inputModel{textInput: ti})
	p.Run()
}

type inputModel struct {
	textInput textinput.Model
	quitting  bool
}

func (m inputModel) Init() tea.Cmd {
	return nil
}

func (m inputModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmd tea.Cmd

	switch msg := msg.(type) {
	case tea.KeyPressMsg:
		switch msg.Code {
		case tea.KeyEnter:
			m.quitting = true
			return m, tea.Quit
		}
	}
	m.textInput, cmd = m.textInput.Update(msg)
	return m, cmd
}

func (m inputModel) View() string {
	str := m.textInput.View()
	if m.quitting {
		return str + "\n"
	}
	return str
}

func main() {
	for i := 0; i < 2; i++ {
		Input(fmt.Sprintf("Test %d: ", i), "default")
	}
}
```

**Comment by joshallenit** [comment]
> [...]
> Hey [@joshallenit](https://github.com/joshallenit), thank you for bringing this to our attention again. While I cannot reproduce this with the latest v2-exp [2ce107c](https://github.com/charmbracelet/bubbletea/commit/2ce107c85fedc825fcba0c16846d43ca484d3093), could you provide a minimal reproducible example for this case?
> 
[...]

I can reproduce the issue using Git Bash. Have you tested your example using Git Bash as the terminal?
