### ISSUE TITLE
v2: all examples using tea.RequestBackgroundColor have unexpected results/hang

### ISSUE THREAD

**Issue by lrstanley** [charmbracelet/bubbletea#1406]
**Describe the bug**

All examples using `tea.RequestBackgroundColor` on the `v2-exp` branch, or with the `v2.0.0-beta.2` tag seem to be non-functional for me. They either hang, or close without error.

paginator example:
https://cdn.liam.sh/share/2025/04/WindowsTerminal_fbHsnPqRoU.mp4

list-fancy example:
https://cdn.liam.sh/share/2025/04/WindowsTerminal_mlqlowdNav.mp4

tabs example:
https://cdn.liam.sh/share/2025/04/WindowsTerminal_4HAUYpNmQH.mp4

list-simple example:
https://cdn.liam.sh/share/2025/04/WindowsTerminal_u0SdLhFZiE.mp4

etc.

Additional info:

- When it hangs, I cannot press any key to close the app. ctrl+c, esc, q, etc.
- Other examples work fine within v2-exp, just seems to be anything that requests the background color.
- v1 seems to work fine for these examples.
- when testing v2 with bubblezone, I also added `tea.RequestBackgroundColor` to my examples, and although it didn't cause these same problems as the examples here (hanging, and/or just exiting), the message was never received by the app.

**Setup**

Please complete the following information along with version numbers, if applicable.
 - OS: Windows 11 Pro 24H2 (26100.3775), within WSL 2.0 (5.15.167.4-microsoft-standard-WSL2)
 - Shell: bash 5.0.17
 - Terminal Emulator(s):
   - Windows Terminal 1.22.11141.0 (& 1.18.10301.0)
   - Alacritty v0.15.1
 - Terminal Multiplexer: n/a

Other info:

```console
$ echo $TERM
screen-256color
```

**To Reproduce**

1. Clone bubbletea repo, switch to `v2-exp` branch
2. `cd examples/list-fancy` (just one of the few with issues)
3. `go run *.go` (go1.24.2)
4. For list-fancy, it hangs.

**Expected behavior**

All examples to be functional.

**Comment by desertwitch** [comment]
I can reproduce it, it doesn't look like a deadlock and the stack trace looks as expected for normal bubbletea operation.
It seems that the `BackgroundColorMsg` never arrives, which the examples are waiting for to become "ready" and start rendering.

**Comment by meowgorithm** [comment]
You're spot on, @desertwitch; we're fixing accordingly.

**Comment by aymanbagabas** [comment]
> Although [074f7d7](https://github.com/charmbracelet/bubbletea/commit/074f7d73be3b564d16048f35183065ba2bbdaf6c) may make the examples work, do Windows Terminal and Alacritty (for example) not support querying the background? Seems really odd that they wouldn't support that.
> 

They do, actually. The problem with your setup is `TERM=screen`. If you're indeed using GNU Screen as a multiplexer, then that explains this. Screen requires escaping any unknown sequences, like OSC 11, in a DCS sequence. However, we don't support that in Bubble Tea _yet_. Here's a list of supported [Screen sequences](https://www.gnu.org/software/screen/manual/screen.html#Control-Sequences-1).

> 1. Is there a specific emulator on Windows that y'all know for a fact should support that capability that I could confirm with?

Yes, you can try this on any terminal with something like `cat | printf '\x1b]11;?\x07'`

> 2. In v1, how did this work? Did it just give up after 500ms and assume it was dark for `AdaptiveColor`, or? Because dark was used on Windows Terminal for me with v1, and just wondering how v1 came to that conclusion if the background check query didn't work. Did it just use dark until it got a response saying otherwise?

Bubble Tea v1 uses Termenv which always queries the background color for `os.Stdout` and has a timeout of 5 seconds. When it doesn't receive a response within the time limit, it returns [`dark=true`](https://github.com/muesli/termenv/blob/master/termenv_unix.go#L121). On Windows however, Termenv always returns [`dark=true`](https://github.com/muesli/termenv/blob/master/termenv_windows.go#L54) because it lacked support for querying the terminal on Windows.

**Comment by lrstanley** [comment]
> They do, actually. The problem with your setup is TERM=screen. If you're indeed using GNU Screen as a multiplexer, then that explains this. Screen requires escaping any unknown sequences, like OSC 11, in a DCS sequence. However, we don't support that in Bubble Tea yet. Here's a list of supported [Screen sequences](https://www.gnu.org/software/screen/manual/screen.html#Control-Sequences-1).

Gotcha -- I use `screen-256color`, because without that on Windows Terminal + WSL2, it seems to default to `xterm-256color`, which in the past with v1, for some reason wasn't allowing full 256bit color (though maybe isn't an issue anymore -- I will test). Not actually using `screen` in this scenario.

With that said, using the default of `xterm-256color` or a blank `TERM` value, both still hang the same exact way, which means in any of those cases, it's not responding with the background color.

> Yes, you can try this on any terminal with something like cat | printf '\x1b]11;?\x07'

What is this supposed to output exactly? With the default `TERM` of `xterm-256color` for Windows Terminal + WSL2, I get this (same with `screen-256color` and blank value):

![](https://cdn.liam.sh/share/2025/05/WindowsTerminal_y58qyXCWx7.png)


> Bubble Tea v1 uses Termenv which always queries the background color for os.Stdout and has a timeout of 5 seconds. When it doesn't receive a response within the time limit, it returns [dark=true](https://github.com/muesli/termenv/blob/master/termenv_unix.go?rgh-link-date=2025-05-01T17%3A32%3A05.000Z#L121). On Windows however, Termenv always returns [dark=true](https://github.com/muesli/termenv/blob/master/termenv_windows.go?rgh-link-date=2025-05-01T17%3A32%3A05.000Z#L54) because it lacked support for querying the terminal on Windows.

That makes sense, because I've never seen that 5s delay on Windows/WSL2, though I have seen the delay sometimes on different Linux environments.

**Comment by aymanbagabas** [comment]
> Gotcha -- I use `screen-256color`, because without that on Windows Terminal + WSL2, it seems to default to `xterm-256color`, which in the past with v1, for some reason wasn't allowing full 256bit color (though maybe isn't an issue anymore -- I will test). Not actually using `screen` in this scenario.
> 

That's a separate issue and _might_ be related to [Termenv](https://github.com/muesli/termenv/blob/master/termenv_unix.go#L39).

> With that said, using the default of `xterm-256color` or a blank `TERM` value, both still hang the same exact way, which means in any of those cases, it's not responding with the background color (testing before the patch so I can easily tell if it's responding with it or not).
> 

The problem with Windows is that it doesn't set a `TERM` variable. In our new Colorprofile package, we assume color support for Windows and also look for the Windows Terminal session variable (`WT_SESSION`) to detect color support. So, this shouldn't be a problem with Bubble Tea v2.

> What is this supposed to output exactly? With the default `TERM` of `xterm-256color` for Windows Terminal + WSL2, I get this (same with `screen-256color` and blank value):
> 
> ![](https://camo.githubusercontent.com/e0df87ff036dd50dd122d303cc4c8d68bee6ed8b28701467dbc987aec7654387/68747470733a2f2f63646e2e6c69616d2e73682f73686172652f323032352f30352f57696e646f77735465726d696e616c5f793538717958435778372e706e67)

That's the correct output response, this means that your terminal reports `#212121` for your background color.

**Comment by lrstanley** [comment]
> The problem with Windows is that it doesn't set a TERM variable. In our new Colorprofile package, we assume color support for Windows and also look for the Windows Terminal session variable (WT_SESSION) to detect color support. So, this shouldn't be a problem with Bubble Tea v2.

At least with Windows Terminal + WSL2, `TERM=xterm-256color` is the default for me.

> That's the correct output response, this means that your terminal reports #212121 for your background color.

If that's the correct response, then why didn't the examples work before, if they were hanging because they were waiting for the response WRT background color?  Guess I'm a little confused. In my testing, I never see a message response to `tea.RequestBackgroundColor`, regardless of the value of `TERM`.

**Comment by desertwitch** [comment]
> > The problem with Windows is that it doesn't set a TERM variable. In our new Colorprofile package, we assume color support for Windows and also look for the Windows Terminal session variable (WT_SESSION) to detect color support. So, this shouldn't be a problem with Bubble Tea v2.
> 
> At least with Windows Terminal + WSL2, `TERM=xterm-256color` is the default for me.
> 
> > That's the correct output response, this means that your terminal reports #212121 for your background color.
> 
> If that's the correct response, then why didn't the examples work before, if they were hanging because they were waiting for the response WRT background color? Guess I'm a little confused. In my testing, I never see a message response to `tea.RequestBackgroundColor`, regardless of the value of `TERM`.

I also think there's more to the issue than this being a compatibility problem that needs a timeout (not that that's a bad thing either).
Examples did not work for me within my VS Code terminal (which I think uses `xterm.js`) connected to a Debian machine, despite:

```
desertwitch@vDebianDev:~/bubbletea-dw/examples/paginator$ echo $TERM
xterm-256color
desertwitch@vDebianDev:~/bubbletea-dw/examples/paginator$ cat | printf '\x1b]11;?\x07'
^[]11;rgb:ffff/ffff/ffff^[\
```

So we also see here colors are being reported, but a `BackgroundColorMsg` never arrives, so I think there's an issue elsewhere.

**Comment by meowgorithm** [comment]
Hey @lrstanley @desertwitch — this should be fixed in [Bubble Tea v2 Beta 3](https://github.com/charmbracelet/bubbletea/releases/tag/v2.0.0-beta.3). When you have a moment, do you mind confirming?

**Comment by lrstanley** [comment]
> Hey [@lrstanley](https://github.com/lrstanley) [@desertwitch](https://github.com/desertwitch) — this should be fixed in [Bubble Tea v2 Beta 3](https://github.com/charmbracelet/bubbletea/releases/tag/v2.0.0-beta.3). When you have a moment, do you mind confirming?

Beta 3 seems to mask the issue (it no longer waits for background color), but the issue is still present in that despite it looking like the terminal supports responding with the terminal color (from above commands I ran earlier in this issue), bubbletea never receives the color.

So right now, it looks like it will no longer hang waiting for the background color message, but the app will never know what the background color is, if it's dark, etc, likely leading to wrong themes being used for apps that support dual colors.

Example repro: https://github.com/lrstanley/bubblezone/blob/v2-exp/examples/full-lipgloss/main.go#L63

1. Replace line 63 with a `panic("received background color info")`
3. When I run this, it never panics, indicating it hasn't received any background color info

---

Additionally, it's unclear from beta 3 -- if one doesn't specify `tea.RequestBackgroundColor` in `Init()`, is that still being requested behind the scenes now? As it was removed from the examples, but the changelog didn't outline that the logic now happens somewhere else.

**Comment by aymanbagabas** [comment]
Hey everyone! Could you please try the latest version of `v2-exp`? `go get github.com/charmbracelet/bubbletea/v2@v2-exp`

**Comment by lrstanley** [comment]
No change (using latest commit as of this message, in v2-exp), still non-functional under WSL2. I will respond in #1440 with more info as well.
