### ISSUE TITLE
Windows use `window.getConsoleMode` results is not expected

### ISSUE THREAD

**Issue by fzdwx** [charmbracelet/bubbletea#408]
On Windows run tea.program use ` windows.GetConsoleMode`  -> 992
but default mode is `503`, so after running, the input direction key will be recognized as `[[A`

![image](https://user-images.githubusercontent.com/65269574/185522147-1080a68d-4735-49a9-8751-72451ee25586.png)

code: 
```go
package main

import (
	"fmt"
	"golang.org/x/sys/windows"
	"unicode/utf16"
)

var fileShareValidFlags uint32 = 0x00000007

func main() {
	var originalMode uint32

	handle, _ := windows.CreateFile(
		&(utf16.Encode([]rune("CONIN$\x00"))[0]), windows.GENERIC_READ|windows.GENERIC_WRITE,
		fileShareValidFlags, nil, windows.OPEN_EXISTING, windows.FILE_FLAG_OVERLAPPED, 0)

	_ = windows.GetConsoleMode(handle, &originalMode)

    // 503
	fmt.Println(originalMode)

	// problematic mode
	//windows.SetConsoleMode(handle, 992)
}
```

_最初由 fzdwx 在 https://github.com/charmbracelet/bubbletea/issues/393#issuecomment-1220136297 发布_

**Comment by meowgorithm** [comment]
Just so we understand correctly, you're saying that arrow keys don't work properly after a Bubble Tea program exits, right?

**Comment by fzdwx** [comment]
> Just so we understand correctly, you're saying that arrow keys don't work properly after a Bubble Tea program exits, right?

Yes, my English may not be good, the description is not very accurate, sorry

**Comment by muesli** [comment]
> Yes, my English may not be good, the description is not very accurate, sorry

Don't worry, I think I see the problem and will provide a fix soon!

**Comment by muesli** [comment]
This should be fixed by #455. We try to restore the original mode on shutdown now. Please let us know if this works for you!

**Comment by fzdwx** [comment]
The problem seems to still exist...

```
git clone https://github.com/charmbracelet/bubbletea.git
cd bubbletea\examples\textinput && go run .
```

press `<Up>` -> `^[[A`

![image](https://user-images.githubusercontent.com/65269574/192463219-babaf731-e986-4460-9602-d27e0eb9ed6a.png)

---

Do I need to wait until release to test?

**Comment by muesli** [comment]
No, that test was fine, and clearly there's still something wrong then. I'll re-open and investigate. How do you exit the textinput example?

**Comment by fzdwx** [comment]
> No, that test was fine, and clearly there's still something wrong then. I'll re-open and investigate. How do you exit the textinput example?

When I'm done typing, hit enter.

**Comment by fzdwx** [comment]
OK, it works, Thanks!

**Comment by muesli** [comment]
> OK, it works, Thanks!

Thanks for confirming!
